### ISSUE TITLE
feature: data 패키지

### ISSUE THREAD

**Issue by synnn0910** [SW-Team2/se-team2-tetris#14]
data패키지를 추가했습니다. 자세한 내용은 PR에 적어 놓았습니다.

**Comment by ojj1123** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [기본적인 data패키지 구조](https://trello.com/c/sJEsH3aw/31-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-data%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B5%AC%EC%A1%B0)
