### ISSUE TITLE
게임화면 제작

### ISSUE THREAD

**Issue by synnn0910** [SW-Team2/se-team2-tetris#15]
data.screens.GameScreen.java 부분을 구현했습니다.
다른 screens패키지 내 클래스들(MainMenuScreen, SettingMenuScreen...etc)을 제작하는데 참고하세요.
세부적인 배치는 하지 않았습니다.

약간의 

- [ ] 게임보드에 서로 다른 색상의 블럭들이  잘 보임
- [ ] 다음 블럭을 제대로 보여줌
- [ ] 스코어가 제대로 업데이트 됨

**Comment by dlxodnjs007** [comment]
screens 디렉토리에 있는 Screen자바파일들에 들어있는
```
super.setBackground(Color.red);
super.add(mTemp);
```
여기에서 super가 가리키는게 무엇인지 알려주실수 있나요
