### ISSUE TITLE
feat: 메인메뉴에서 버튼으로 화면 전환

### ISSUE THREAD

**Issue by ojj1123** [SW-Team2/se-team2-tetris#19]
- [x] 키보드 클릭 시 버튼으로 focus함
- [x] focus한 버튼에서 enter를 누르면 다음 패널로 이동
- [ ] 각 페널에서 메인 패널로 돌아오는 API 개발

**Comment by synnn0910** [comment]
버튼에 focus하고 unfocus하는 방식말고 각 버튼에 대한 index를 지정하고 유저가 버튼을 옮겨다닐 때 마다 index를 맞게 바꿔주다 enter를 누르면 현재 index의 버튼을 실행하는 방식도 괜찮을거 같아여

**Comment by ojj1123** [comment]
@synnn0910 지금 keystroke로 하다가 시영님이 말씀하신 거랑 비슷하게 구현중이에요!
