### ISSUE TITLE
HOTFIX❗️:  게임 조작키가 작동하지 않는 버그

### ISSUE THREAD

**Issue by ojj1123** [SW-Team2/se-team2-tetris#20]
## Bug report
<img width="912" alt="스크린샷 2022-03-29 01 58 28" src="https://user-images.githubusercontent.com/33178048/160449233-f6539165-cd4c-4da7-b8b6-e74c2bbb6f56.png">

- #13 merge이후 main에서 작업 브랜치 판 후 작업을 하는데, 게임 화면으로 넘어가면 조작키가 작동하지 않습니다.
- #13 merge이후 main에서 게임을 실행해 보면 조작키는 잘 작동합니다.
- 작업브랜치에서 작업하면서 건드린 부분이 있는 것같습니다.

**Comment by synnn0910** [comment]
현재 작업중이신 브랜치 push해 주실수 있나요?

**Comment by ojj1123** [comment]
일단 메인에서 다른 메뉴로 가는 기능 먼저 push 할게요.
