### ISSUE TITLE
[Discuss] code 컨벤션에 관한 논의

### ISSUE THREAD

**Issue by ojj1123** [SW-Team2/se-team2-tetris#29]
## 배경
오늘 회의에서 멤버변수와 enum 에 대한 prefix를 설정해줄 것인지 안할 것인지에 대해 논의했었죠. 대다수 분들이 찬성을 했으나 설득이 필요하여 여러 자료를 조사해봤습니다. "그냥 하면 되지 않나"라고 생각하기 보다는 제가 왜 이런 논의를 하고자 하는지 이해해주시면 감사하겠습니다.

또한 code style도 맞춰야 겠다고 생각했습니다.

TL;DR
1. prefix를 붙이는 것이 불필요하다고 느낌.
2. prefix가 오히려 가독성을 해칠 수 있음.
3. 소통의 장애가 될 수 있음.
4. google java code style로 통일 및 sonarLint 적용

## 의견
회의 때 정확하게 의견전달을 못해서 글로 전달하고자합니다. prefix에 대해 반대하는 이유는 다음과 같습니다.
1. 모든 멤버 변수, enum에 대해 m과 e를 붙이는 것이 불필요하다고 느꼈습니다. 왜냐하면 IDE에서 해당 변수의 성격(type, modifier  등)을 확인할 수 있는 기능이 있기 때문입니다. 그러면 lint 설정을 하면 우려하신 지역변수로 인해 멤버변수가 덮이는 상황을 막을 수 있겠죠. IDE에서 제공해주는데 prefix를 붙일 필요가 있을까요? IDE 기능을 더 적극적으로 사용하는 측면이 장기적으로 봤을 때 프로젝트 규모가 더 켜졌을 때 도움이 되지 않을까요?

2. 이런 prefix를 붙이는 것이 오히려 코드의 가독성을 해칠 수 있다고 생각합니다.
어떤 변수가 멤버변수인지, enum 변수인지 바로 알 수 있어 가독성이 향상되는 것처럼 느껴질 수도 있습니다. 하지만 만약 해당 변수가 멤버변수이면서 enum 이라면 어떻게 해야할까요? prefix 로 `me` 를 붙어야 할 수도 있습니다. 심지어 `em`이 될 수도 있겠죠. 그렇다면 이미 영어 단어에는 me와 em의 의미가 있으니, 오히려 변수의 의미를 파악하는 장애물이 될 수도 있습니다. 극단적인 예시이지만 충분히 가능한 상황이죠. 차라리 this를 사용하는 것이 더 파악하기 용이할 수 있습니다.

3. 소통의 장애가 될 수 있습니다.
어떤 코드에 대해 이야기 할 때, 변수명을 언급할 경우가 있습니다. 하지만 prefix로 인해 변수명을 기억하기 힘들 수도 있고, 변수명을 언급할 때마다 m과 e를 함께 전달해야 합니다. 심지어 현재 프로젝트에서 사용 중인 swing의 컴포넌트를 언급할 때마다 m을 붙어서 언급해야 합니다. 이 부분에서 소통의 장애가 될 수 있다는 것입니다.

## 해결책
1. 저희가 어떤 코드 스타일을 따를지 정하지 않아서 가끔 다른 사람이 작업한 코드를 가져오면 code format이 맞지 않는 경우가 있습니다. ide에서 기본적으로 제공하는 format도 다르고요. 그래서 format을 google style guide로 맞추고자 합니다.
[google Java Style Guide](https://google.github.io/styleguide/javaguide.html)

IDE마다 format설정이 다르기 때문에 두가지 링크를 걸도록 하겠습니다.
- [intellij에서 google java style guide 적용](https://velog.io/@injoon2019/IntelliJ%EC%97%90-Google-Java-Style-Guide-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
- [vscode에서 google java style guide 적용](https://code.visualstudio.com/docs/java/java-linting#_applying-formatter-settings)

2. lint 설정을 통해 코드의 오류, 버그, 스타일 오류 등을 잡아줍니다.
java의 lint 도구로 sonarLint 가 가장 많이 사용된다고 합니다. 각 IDE마다 plugin을 지원해줘서 설치해서 사용할 수 있어요!
[sonarLint](https://www.sonarlint.org/)

## 참고
변수명에 해당 변수의 성격을 나타내는 표기법을 [헝가리안 표기법](https://en.wikipedia.org/wiki/Leszynski_naming_convention) 이라고 합니다. ms에서 만들긴 했지만 요즘엔 널리 사용되지 않는다고 하더라고요.
[google java style guide](https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names) 에서는 prefix사용을 안한다고 합니다.

**Comment by synnn0910** [comment]
1. m과 e를 붙이는 이유는 가독성과 실수방지입니다. 말씀하신 IDE의 도움으로 실수를 줄이는 방법도 도움이 되지만 코드를 작성하는 사람이 신경을 쓰게 강제하는 방법이 우선시 되어야 한다고 생각합니다. IDE기능을 적극 활용하는 데 찬성하지만 그렇다고 멤버 변수라는 표시를 하지 않는건 가독성과 실수방지에 안좋을거 같습니다.

2. 접두어는 말씀하신 것처럼 멤버 변수이면서 열거체일 경우 me를 붙이고 boolean변수인 경우 mb를 붙입니다(자바에선 boolean과 int, char등간에 암시적 형변환이 불가능 하기 때문에 b접두어는 컨벤션에 넣지 않았습니다). 코딩 규칙을 정한 상황에서 접두어 me를 다른 의미로 해석할 일은 전 지금까지 없었습니다.

3. 코드를 읽는 사람이 코드를 작성한 사람이 어떤 의도로 코드를 작성했는지 더 명확히 알 수 있기 때문에 가독성이 올라가 접두어 m을 붙임으로서 소통이 더욱 원활해진다 생각합니다. 코드에 관해 다른 사람과 얘기한 적이 많이 없어서 소통에 지장이 없을거라 확답은 못하지만 오늘 회의 중 대화할 때는 별 문제를 느끼지 못했습니다.

접두어 m,e를 사용하는건 헝가리안 표기법이 아닙니다. 헝가리안 표기법은 모든 변수에 int면 i, char면 c, handle이면 h의 접두어를 붙이는 방법입니다. 헝가리안 표기법이 사용되지 않는 이유는 모든 변수에 타입을 명시할 필요성이 없고 타입을 붙여 오히려 가독성을 해치며 변수의 타입을 바꾸면 변수의 이름을 바꿔 줘야 하는 등의 이유로 알고 있습니다. 접두어 m,e를 붙이는건 이런 단점이 발생할 여지가 없고 가독성은 높여준다 생각합니다.

컨벤션을 처음 정할 때 말했듯이 자바진영에선 올려주신 구글처럼 접두어 m보단 this.을 사용하는데 이유는 저도 모르겠습니다. 저는 개인적으로 m은 변수의 이름에 포함되므로 무조건 붙여야 하지만 this.은 붙이지 않아도 실행되기 때문에 접두어 방식이 더 낫다고 생각합니다. 또 this.방식과 m방식의 차이가 크지 않은데 지금까지 쓴 코드에 모두 this.을 추가하고 변수명을 바꾸는건 비효율적인거 같습니다.

컨벤션은 언리얼 엔진, 둠3 코드표준에서 참고했습니다. 둘 다 오픈소스로 많은 사람들이 읽어보고 가독성이 높다고 평가합니다. 
https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/CodingStandard/
둠3는 링크가 사라졌네요...

컨벤션을 제가 코딩 경험이 많은 것도 아니면서 거의 마음대로 정한거지만 this.으로 바꾼다고 크게 나아질 부분도 없고 접두어를 붙이는게 제가 쓴 코드를 제가 볼 때도 도움이 되고 다른 팀원 분들도 도움이 된다고 말하셔서 저는 이대로 갔으면 좋겠습니다.

**Comment by synnn0910** [comment]
.

**Comment by synnn0910** [comment]
m, this. 중 원하는걸 쓰는 것도 괜찮을거 같아요. 일관성 있게 하면 두 방법다 비슷하니..

**Comment by ojj1123** [comment]
사실 아까 PR올리신 코드 보고 `me`와 `mb` 로 되어 있는  변수가 바로 파악이 되지 않았습니다. 클래스 상단에 올라가서야 이게 member와 enum/boolean이라는 것이 파악이 되었죠.

슬랙에서 코드에 대해 이야기할 때나 코드리뷰를 할 때, m을 붙혀가며 이야기 하는 것에서 불편함을 느꼈습니다.

지금까지 작성한 코드를 다 바꾸자는 얘기보다는 일단 그건 legacy로 남겨두고 앞으로 컨벤션을 수정하자는 얘기였습니다.

code style을 하나로 통일하고, lint를 적용한다면 실수를 방지할 수 있습니다.(lint가 오류를 잡아줌)

**Comment by synnn0910** [comment]
변수형을 확인하고 싶을 때 변수선언부로 가야하는건 this.을 사용할때 입니다. 그 부분에선 mb, me를 사용하는게 한번 파악하면 그 후론 확인하지 않아도 되는 방법입니다. 

지금까지 쓴 코드에 2차 요구사항을 반영하려면 원래 코드에 추가로 코드를 작성해야 하는데 컨벤션이 바뀌어버리면 일관성이 없어져 버리니 각 파일마다라도 일관성을 유지할 수 있도록 m과 this.중 원하는 방식을 사용하는걸로 컨벤션을 바꾸는 게 맞을거 같습니다.

**Comment by ojj1123** [comment]
> 변수형을 확인하고 싶을 때 변수선언부로 가야하는건 this.을 사용할때 입니다.

변수형을 확인한다기보다는 이게 어떤 의미인지 바로 파악이 안됐어요.
변수형은 IDE기능으로 선언부 안가봐도 알 수 있으니까요. vscode든 intellij든요!

discussion을 연 이유는 습관적으로 사용하던 컨벤션에 대해 이야기해보고 싶었습니다. 저도 주변에 물어보면서 말씀드린거구요. 그런 notation을 안써도 충분히 의도 파악이 가능하고, 실수도 줄일 수 있음을 서로 알았으면 했습니다:)

그럼 둘을 혼용하는 방식으로 합시다!

**Comment by ojj1123** [comment]
> ms에서 만들긴 했지만 요즘엔 널리 사용되지 않는다고 하더라고요.

참고로 제가 위처럼 말을 했었는데, 아래 링크는 최근 General Naming Conventions에 대한 ms의 공식가이드라인입니다.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions
> ❌ DO NOT use Hungarian notation.

만든 쪽에서도 사용을 권장하고 있지는 않네요.

**Comment by dlxodnjs007** [comment]
아 me em은 생각 못 했네요... 혹시 현재 있는 컨벤션을 this.로 바꾸면 시간이 오래 걸릴까요?
프로그램이 커지면 나중에 문제가 될 수도 있다는 정진님의 의견에서, 조금 무책임한 말일수도 있지만 제 생각에는 그렇게 커질 부분이 이제 없을 것 같은 느낌이 듭니다.

**Comment by ojj1123** [comment]
지금까지 한 컨벤션을 다 바꾸면 바꿀 수 있긴합니다. ide에 refactor 기능이 있어서요. 만약 바꾼다면 일단은 남겨두고, 마지막에 바꿔도 됩니다.

책임에 관한거는 논외로 합시다. "프로그램이 커진다"라는 말은 기능이 많아진다는 의미도 있지만, Line Coverage가 증가해서 코드의 복잡도나 테스트할 수 있는 범위가 증가함을 의미하기도 합니다. 즉, 기능이 많든 적든 어떻게 코드를 설계하냐에 따라 구현과 유지/보수, 테스트 방식이 달라질 수 있다는 이야기입니다. 협업하는 상황이라면 "다른 사람이 작성한 코드"를 보고 읽고 이해해야하죠. 때로는 코드가지고 이야기도 나누겠죠. 그런 차원에서 prefix를 붙이는 것이 redundant 하다고 느껴서 논의를 해보자는 거였습니다. 제가 이슈 맨위에서 언급한 것이었습니다.

또한 본인이 습관적으로 작성하는 방법에 대해서도 이야기 해보고 싶었습니다. 내가 봤을 때는 편하고 이해하기 좋은데, 다른 사람들이 봤을 때는 그렇지 않을 수 있는거죠. 이런 방식을 왜 이렇게 나왔고, 장단점이 무엇인지 논의하자는 취지입니다.

**Comment by dlxodnjs007** [comment]
그러면 저는 두 분이 쓰는 코드를 보면서 편한 쪽으로 사용하도록 하겠습니다. 저도 더 하다보면 뭐가 더 나은 것인지 더 나은 판단을 할 수 있을 것 같습니다. 추후에 금방 바꿀 수 있는 부분이니까 refactoring때 의견을 나눠봅시다~ 
이런 의견을 나누는 것이 익숙치 않은데, 되게 건전하고 재밌습니다~ 감사합니다~
