### ISSUE TITLE
[Refactor]: 변수명, 메소드명, 클래스명 수정/파일 구조 수정

### ISSUE THREAD

**Issue by ojj1123** [SW-Team2/se-team2-tetris#32]
## 배경
처음 코드리뷰를 하지 않고 넘어간 부분(테트리스 게임 관련 부분, `package tetrisgame`)의 코드에서 변수명, 메소드명, 클래스명 등 의미가 모호한 부분이 있습니다. 아이템 모드를 추가해야 해서 좀 더 확정성이 있고 의미파악하기 용이하도록 전반적으로 리팩터링을 진행하려고합니다.

축약형 및 오타로 인해 의미파악하기 어려운 몇몇 변수, 메소드, enum, 클래스 등이 있어 수정을 하려고 합니다.
또한 `src/data` 안에 있는 데이터에 접근하는 방식을 직접 멤버변수에 접근하는 것이 아니라 javabeans 관례에 따라 `getter/setter`로 바꾸는 작업에 대한 의견을 댓글로 남겨주세요.

~~시험 끝나고 4/15 or 4/16에 진행하려고 합니다.~~ 추후에 이야기합시다.

## 수정 항목(추가 중)
- [ ] 모든 축약형 수정 -> 축약형 사용은 지양하려 합니다.
- [ ] `screen.java` 와 `WindowManager.java`의 역할 및 이들을 합칠지 논의
  - `graphics` 안에 `screens`가 있는데 이 둘이 약간 모호하다고 느껴졌습니다. 그래서 `package screens`안에 있는 `*Screen.java` 파일을 밖으로 빼는 것으로 진행해볼까 합니다.
  - Screen에 대한 클래스가 다른 곳에도 중복으로 있습니다.(`src/data/setting/SettingInfoDesc.java` 내부에 Screen 클래서 정의되어 있음)
- [ ] enum 변수는 따로 `common` 이라는 `package`를 만들어서 관리
- [ ] 기타 애매모호한 naming은 회의를 하면서 수정할 예정
- [ ] (논의 후 결정)prefix에 대한 수정

기타 추가적인 의견이 있다면 댓글 부탁드립니다.

**Comment by synnn0910** [comment]
num, temp, curr, prev와 같이 자주 쓰이고 그 의미가 명확하거나 문맥상 알 수 있는 변수명은 축양형을 사용하는게 가독성에 좋습니다. 

src/data 에 SettingInfoDesc에 public 변수들을 말씀하시는거 같은데 전에 말씀드렸듯이 c의 struct처럼 사용하는게 편하니 public으로 지었습니다. 아직 이 클래스를 사용하는 다른 클래스가 없으니 맡으신 분이 마음대로 하시면 될 것 같습니다.

Screen클래스는 각 Screen 클래스들이 상속하는 추상클래스 입니다. 모든 스크린들이 getUserInput메서드를 override하도록 강제하기 위해 만들 클래스입니다.
WindowManager클래스는 Screen클래스를 상속한 각 Screen들을 컴포즈하고 화면에 적절하게 뿌려주는 역할을 합니다.
둘이 완전 다른 겁니다.

SettingInfoDesc에 있는 Screen은 내포클래스라 완전 다른겁니다
SettingInfoDesc.getInstance().new Screen() 이런식으로 써야합니다.

tetrisgame/enumeration에 있는 enum들은 tetrisgame패키지 내부에서만 사용해야 합니다.

**Comment by synnn0910** [comment]
다음주 시험 생각하면 일주일 정도밖에 시간이 안남았는데 리팩토링 말고 기능 구현에 집중하죠..

**Comment by ojj1123** [comment]
시영님도 새벽에 활동하시나보네요..ㅋㅋㅋㅋ 얼마 안남은거는 사실이니까 1,2차 끝내고 이야기 해봅시다.
